import arithmeticEqual from './equal';
import arithmeticEven from './even';
import arithmeticOdd from './odd';
import arithmeticPositive from './positive';
import arithmeticNegative from './negative';
import arithmeticAbove from './above';
import arithmeticUnder from './under';
import arithmeticWithin from './within';
import arithmeticDecimal from './decimal';
import arithmeticInteger from './integer';
import arithmeticFinite from './finite';
import arithmeticInfinite from './infinite';

export const isEqual = arithmeticEqual;
export const isEven = arithmeticEven;
export const isOdd = arithmeticOdd;
export const isPositive = arithmeticPositive;
export const isNegative = arithmeticNegative;
export const isAbove = arithmeticAbove;
export const isUnder = arithmeticUnder;
export const isWithin = arithmeticWithin;
export const isDecimal = arithmeticDecimal;
export const isInteger = arithmeticInteger;
export const isFinite = arithmeticFinite;
export const isInfinite = arithmeticInfinite;
