// import regexp
import {
  isUrl,
  isEmail,
  isCreditCard,
  isAscii,
  isAlphaNumeric,
  isTimeString,
  isDateString,
  isUsZipCode,
  isCaPostalCode,
  isUkPostCode,
  isNanpPhone,
  isEppPhone,
  isSocialSecurityNumber,
  isAffirmative,
  isHexadecimal,
  isHexColor,
  isIpv4,
  isIpv6,
  isIp,
  isDataURI,
  isMagnetURL,
  isMd5,
  isMacAddress,
  isBase64,
  isUUID
} from './index';

// export regexp
export default {
  url: isUrl,
  email: isEmail,
  creditCard: isCreditCard,
  ascii: isAscii,
  alphaNumeric: isAlphaNumeric,
  timeString: isTimeString,
  dateString: isDateString,
  usZipCode: isUsZipCode,
  caPostalCode: isCaPostalCode,
  ukPostCode: isUkPostCode,
  nanpPhone: isNanpPhone,
  eppPhone: isEppPhone,
  socialSecurityNumber: isSocialSecurityNumber,
  affirmative: isAffirmative,
  hexadecimal: isHexadecimal,
  hexColor: isHexColor,
  ipv4: isIpv4,
  ipv6: isIpv6,
  ip: isIp,
  dataURI: isDataURI,
  magnetURL: isMagnetURL,
  md5: isMd5,
  macAddress: isMacAddress,
  base64: isBase64,
  uuid: isUUID
}
