import timeDate from './date';
import timeToday from './today';
import timeYesterday from './yesterday';
import timeTomorrow from './tomorrow';
import timePast from './past';
import timeFuture from './future';
import timeDay from './day';
import timeMonth from './month';
import timeYear from './year';
import timeLeapYear from './leapYear';
import timeWeekday from './weekday';
import timeWeekend from './weekend';
import timeInDateRange from './inDateRange';
import timeInLastWeek from './inLastMonth';
import timeInLastMonth from './inLastMonth';
import timeInLastYear from './inLastYear';
import timeInNextWeek from './inNextWeek';
import timeInNextMonth from './inNextMonth';
import timeInNextYear from './inNextYear';
import timeQuarterOfYear from './quarterOfYear';
import timeDayLightSavingTime from './dayLightSavingTime';

export const isDate = timeDate;
export const isToday = timeToday;
export const isYesterday = timeYesterday;
export const isTomorrow = timeTomorrow;
export const isPast = timePast;
export const isFuture = timeFuture;
export const isDay = timeDay;
export const isMonth = timeMonth;
export const isYear = timeYear;
export const isLeapYear = timeLeapYear;
export const isWeekday = timeWeekday;
export const isWeekend = timeWeekend;
export const isInDateRange = timeInDateRange;
export const isInLastWeek = timeInLastWeek;
export const isInLastMonth = timeInLastMonth;
export const isInLastYear = timeInLastYear;
export const isInNextWeek = timeInNextWeek;
export const isInNextMonth = timeInNextMonth;
export const isInNextYear = timeInNextYear;
export const isQuarterOfYear = timeQuarterOfYear;
export const isDayLightSavingTime = timeDayLightSavingTime;
