//import environment
import {
  isIe,
  isEdge,
  isChrome,
  isFirefox,
  isOpera,
  isOperaMini,
  isPhantom,
  isSafari,
  isIos,
  isIphone,
  isIpad,
  isIpod,
  isAndroid,
  isAndroidPhone,
  isAndroidTablet,
  isBlackberry,
  isWindowsPhone,
  isWindowsTablet,
  isWindows,
  isMac,
  isLinux,
  isDesktop,
  isMobile,
  isTablet,
  isOnline,
  isOffline,
  isTouchDevice
} from './index';

// export environment
export default {
  ie: isIe,
  edge: isEdge,
  chrome: isChrome,
  firefox: isFirefox,
  opera: isOpera,
  operaMini: isOperaMini,
  phantom: isPhantom,
  safari: isSafari,
  ios: isIos,
  iphone: isIphone,
  ipad: isIpad,
  ipod: isIpod,
  android: isAndroid,
  androidPhone: isAndroidPhone,
  androidTablet: isAndroidTablet,
  blackberry: isBlackberry,
  windowsPhone: isWindowsPhone,
  windowsTablet: isWindowsTablet,
  windows: isWindows,
  mac: isMac,
  linux: isLinux,
  desktop: isDesktop,
  mobile: isMobile,
  tablet: isTablet,
  online: isOnline,
  offline: isOffline,
  touchDevice: isTouchDevice
}
