import environmentIe from './ie';
import environmentEdge from './edge';
import environmentChrome from './chrome';
import environmentFirefox from './firefox';
import environmentOpera from './opera';
import environmentOperaMini from './operaMini';
import environmentPhantom from './phantom';
import environmentSafari from './safari';
import environmentIos from './ios';
import environmentIphone from './iphone';
import environmentIpad from './ipad';
import environmentIpod from './ipod';
import environmentAndroid from './android';
import environmentAndroidPhone from './androidPhone';
import environmentAndroidTablet from './androidTablet';
import environmentBlackberry from './blackberry';
import environmentWindowsPhone from './windowsPhone';
import environmentWindowsTablet from './windowsTablet';
import environmentWindows from './windows';
import environmentMac from './mac';
import environmentLinux from './linux';
import environmentDesktop from './desktop';
import environmentMobile from './mobile';
import environmentTablet from './tablet';
import environmentOnline from './online';
import environmentOffline from './offline';
import environmentTouchDevice from './touchDevice';

export const isIe = environmentIe;
export const isEdge = environmentEdge;
export const isChrome = environmentChrome;
export const isFirefox = environmentFirefox;
export const isOpera = environmentOpera;
export const isOperaMini = environmentOperaMini;
export const isPhantom = environmentPhantom;
export const isSafari = environmentSafari;
export const isIos = environmentIos;
export const isIphone = environmentIphone;
export const isIpad = environmentIpad;
export const isIpod = environmentIpod;
export const isAndroid = environmentAndroid;
export const isAndroidPhone = environmentAndroidPhone;
export const isAndroidTablet = environmentAndroidTablet;
export const isBlackberry = environmentBlackberry;
export const isWindowsPhone = environmentWindowsPhone;
export const isWindowsTablet = environmentWindowsTablet;
export const isWindows = environmentWindows;
export const isMac = environmentMac;
export const isLinux = environmentLinux;
export const isDesktop = environmentDesktop;
export const isMobile = environmentMobile;
export const isTablet = environmentTablet;
export const isOnline = environmentOnline;
export const isOffline = environmentOffline;
export const isTouchDevice = environmentTouchDevice;
