import typeArguments from './arguments';
import typeArray from './array';
import typeBuffer from './buffer';
import typeBoolean from './boolean';
import typeDate from './date';
import typeError from './error';
import typeFunction from './function';
import typeNan from './nan';
import typeNull from './null';
import typeNumber from './number';
import typeObject from './object';
import typePlainObject from './plainObject';
import typeJson from './json';
import typeRegexp from './regexp';
import typeString from './string';
import typeChar from './char';
import typeUndefined from './undefined';
import typeMap from './map';
import typeSet from './set';
import typeSymbol from './symbol';
import typeSameType from './sameType';

export const isArguments = typeArguments;
export const isArray = typeArray;
export const isBuffer = typeBuffer;
export const isBoolean = typeBoolean;
export const isDate = typeDate;
export const isError = typeError;
export const isFunction = typeFunction;
export const isNan = typeNan;
export const isNull = typeNull;
export const isNumber = typeNumber;
export const isObject = typeObject;
export const isPlainObject = typePlainObject;
export const isJson = typeJson;
export const isRegexp = typeRegexp;
export const isString = typeString;
export const isChar = typeChar;
export const isUndefined = typeUndefined;
export const isMap = typeMap;
export const isSet = typeSet;
export const isSymbol = typeSymbol;
export const isSameType = typeSameType;
